// Auto-generated by scripts/generate-webcontainer-snapshot.mjs
import { readFileSync } from 'node:fs';
import path from 'node:path';

/**
 * Get the binary WebContainer snapshot
 * This provides faster mounting than the tree-based approach
 */
export function getSnapshot(): Uint8Array {
  const snapshotPath = path.join(process.cwd(), 'src', 'data', 'webcontainer-snapshot.bin');
  return readFileSync(snapshotPath);
}

/**
 * Legacy function - kept for compatibility
 * @deprecated Use getSnapshot() for better performance
 */
export function getFiles() {
  // For development, we can still fall back to the tree-based approach
  // but in production, prefer using the binary snapshot
  throw new Error('Use getSnapshot() instead for better performance');
}
