// Auto-generated by scripts/generate-webcontainer-snapshot.mjs
import { readFileSync } from 'node:fs';
import path from 'node:path';

/**
 * Get the binary WebContainer snapshot
 * This provides faster mounting than the tree-based approach
 */
export function getSnapshot(): Uint8Array {
  const snapshotPath = path.join(process.cwd(), 'src', 'data', 'webcontainer-snapshot.bin');
  return readFileSync(snapshotPath);
}

/**
 * Get the WebContainer files via API endpoint
 * This fetches the binary snapshot from the server
 */
export async function getSnapshotFromAPI(): Promise<ArrayBuffer> {
  const response = await fetch('/api/webcontainer-snapshot');
  if (!response.ok) {
    throw new Error('Failed to fetch WebContainer snapshot');
  }
  return response.arrayBuffer();
}
